"""Generate a runnable, headless Python script from a pipeline graph.

The exported script imports the pure functions from
:mod:`napari_vipp.core.operations` (which have no Qt/napari dependency) and
rebuilds the graph computation as a ``run_pipeline`` function plus a small batch
harness so a tuned workflow can be run over a folder of images without napari.
"""

from __future__ import annotations

import inspect
import keyword
import re
from datetime import UTC, datetime

from napari_vipp.core.pipeline import NODE_LIBRARY_BY_ID, PrototypePipeline

_INDENT = " " * 4
_RESERVED_FUNCTION_NAMES = {
    "OUTPUT_NODES",
    "Path",
    "SOURCE_NODES",
    "_table_output_path",
    "argparse",
    "batch_process",
    "is_table_data",
    "load_image",
    "np",
    "read_image",
    "save_image",
    "save_table_output",
    "write_image",
}


def export_pipeline_to_python(
    pipeline: PrototypePipeline,
    *,
    function_name: str = "run_pipeline",
) -> str:
    """Return Python source code that reproduces the pipeline headlessly."""
    if not function_name.isidentifier() or keyword.iskeyword(function_name):
        raise ValueError(f"Invalid exported function name: {function_name!r}.")
    order = pipeline.topological_order()
    var_names = _unique_names(order, prefix="v")

    source_ids = [
        node_id
        for node_id in order
        if not NODE_LIBRARY_BY_ID[pipeline.nodes[node_id].operation_id].has_input
    ]
    source_param_names = _unique_names(source_ids, prefix="src")
    terminal_ids = _terminal_nodes(pipeline, order)
    used_functions = _used_function_names(pipeline, order)
    if function_name in _RESERVED_FUNCTION_NAMES or function_name in used_functions:
        raise ValueError(f"Invalid exported function name: {function_name!r}.")

    body_lines, missing = _build_function_body(
        pipeline,
        order,
        var_names,
        source_param_names,
        function_name,
    )
    header = _build_header(pipeline)
    imports = _build_imports(used_functions)
    helpers = _build_helpers()
    constants = _build_constants(source_ids, terminal_ids)
    main = _build_main(source_ids, function_name)

    sections = [header, imports, constants, "\n".join(body_lines), helpers, main]
    document = "\n\n\n".join(section for section in sections if section)
    if missing:
        note = "\n".join(f"# NOTE: {line}" for line in missing)
        document = f"{document}\n\n\n{note}\n"
    return document.rstrip() + "\n"


def export_batch_runner_to_python() -> str:
    """Return a thin launcher for a saved workflow and batch configuration.

    Unlike :func:`export_pipeline_to_python`, this companion deliberately keeps
    the shared batch engine as the source of truth for pairing, filenames,
    provenance, and failure handling.
    """
    return '''"""Run a saved napari-vipp batch workflow reproducibly."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from napari_vipp.core.batch import run_batch_from_files


def main(argv=None):
    script_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description="Run a saved napari-vipp workflow and batch configuration."
    )
    parser.add_argument(
        "--workflow",
        default=None,
        help="Workflow override (default: the path recorded by the config).",
    )
    parser.add_argument(
        "--config",
        default=str(script_dir / "vipp_batch_config.json"),
        help="Saved VIPP batch config JSON (default: sibling config artifact).",
    )
    args = parser.parse_args(argv)
    try:
        result = run_batch_from_files(args.workflow, args.config)
    except Exception as exc:
        print(f"Batch failed before or during execution: {exc}", file=sys.stderr)
        return 2
    summary = result.summary
    print(
        f"{summary['completed']} completed, "
        f"{summary['partial']} partial, "
        f"{summary['skipped']} skipped, "
        f"{summary['failed']} failed; "
        f"{len(result.saved_paths)} outputs saved; "
        f"manifest: {result.manifest_path}"
    )
    return 1 if result.has_failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _build_header(pipeline: PrototypePipeline) -> str:
    stamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    node_count = len(pipeline.nodes)
    connection_count = len(pipeline.connections)
    return (
        '"""Auto-generated by napari-vipp pipeline export.\n\n'
        f"Generated: {stamp}\n"
        f"Nodes: {node_count}  Connections: {connection_count}\n\n"
        "Run a single image:\n"
        "    python this_script.py input.tif output.tif\n\n"
        "Batch process a folder:\n"
        "    python this_script.py input_dir/ output_dir/ --pattern '*.tif'\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        "from pathlib import Path\n\n"
        "import numpy as np"
    )


def _build_imports(function_names: list[str]) -> str:
    names = sorted(set(function_names))
    imports: list[str] = []
    if names:
        inner = ",\n".join(f"{_INDENT}{name}" for name in names)
        imports.append(f"from napari_vipp.core.operations import (\n{inner},\n)")
    imports.extend(
        (
            "from napari_vipp.core.io import read_image, write_image",
            "from napari_vipp.core.tables import is_table_data, save_table_output",
        )
    )
    return "\n".join(imports)


def _build_constants(source_ids: list[str], terminal_ids: list[str]) -> str:
    sources = ", ".join(repr(node_id) for node_id in source_ids)
    terminals = ", ".join(repr(node_id) for node_id in terminal_ids)
    return (
        f"SOURCE_NODES = ({sources}{',' if len(source_ids) == 1 else ''})\n"
        f"OUTPUT_NODES = ({terminals}{',' if len(terminal_ids) == 1 else ''})"
    )


def _build_function_body(
    pipeline: PrototypePipeline,
    order: list[str],
    var_names: dict[str, str],
    source_param_names: dict[str, str],
    function_name: str,
) -> tuple[list[str], list[str]]:
    source_ids = [
        node_id
        for node_id in order
        if not NODE_LIBRARY_BY_ID[pipeline.nodes[node_id].operation_id].has_input
    ]
    params = []
    for index, node_id in enumerate(source_ids):
        param = source_param_names[node_id]
        params.append(param if index == 0 else f"{param}=None")
    signature = ", ".join(params) if params else ""

    lines = [f"def {function_name}({signature}):"]
    docstring = '"""Execute the exported VIPP graph and return node outputs."""'
    lines.append(f"{_INDENT}{docstring}")

    missing: list[str] = []
    for node_id in order:
        node = pipeline.nodes[node_id]
        spec = NODE_LIBRARY_BY_ID[node.operation_id]
        var = var_names[node_id]
        if not spec.has_input:
            lines.append(f"{_INDENT}{var} = {source_param_names[node_id]}")
            continue

        connections = _required_input_connections(pipeline, node)
        if spec.function is None or connections is None:
            lines.append(f"{_INDENT}{var} = None  # {node.title}: no connected input")
            continue

        call = _build_call(pipeline, node, spec, connections, var_names)
        lines.append(f"{_INDENT}{var} = {call}")
        if node.operation_id == "combine_channels":
            if "channel_axis" not in node.params:
                missing.append(
                    "combine_channels was exported without a stored channel_axis; "
                    "run the pipeline once in napari to store the metadata-derived "
                    "axis before export."
                )
        if spec.is_multi_output and node_id in _terminal_nodes(pipeline, order):
            missing.append(
                f"{node.title} ({node_id}) produces multiple outputs but nothing "
                "consumes them; connect its output ports so the script can route "
                "each channel."
            )

    returns = ", ".join(f"{node_id!r}: {var_names[node_id]}" for node_id in order)
    lines.append(f"{_INDENT}return {{{returns}}}")
    return lines, _dedupe(missing)


def _required_input_connections(pipeline, node):
    connections = pipeline._input_connections(node.id)
    if not connections:
        return None
    multi_input = node.max_inputs is None or node.max_inputs != 1
    if not multi_input:
        return connections[:1]
    required = pipeline._required_inputs_for(node)
    by_port = {connection.target_port: connection for connection in connections}
    if any(port not in by_port for port in range(required)):
        return None
    return [by_port[port] for port in range(required)]


def _build_call(pipeline, node, spec, connections, var_names) -> str:
    fn_name = spec.function.__name__
    accepted = list(inspect.signature(spec.function).parameters)
    data_param = accepted[0] if accepted else ""
    kwargs = {
        key: value
        for key, value in node.params.items()
        if key in accepted and key != data_param
    }
    kwargs_text = ", ".join(f"{key}={value!r}" for key, value in kwargs.items())

    multi_input = node.max_inputs is None or node.max_inputs != 1
    if multi_input:
        inputs = ", ".join(
            _source_ref(pipeline, conn, var_names) for conn in connections
        )
        first_arg = f"[{inputs}]"
    else:
        first_arg = _source_ref(pipeline, connections[0], var_names)

    if kwargs_text:
        return f"{fn_name}({first_arg}, {kwargs_text})"
    return f"{fn_name}({first_arg})"


def _source_ref(pipeline, connection, var_names) -> str:
    """Return the variable expression for one input connection.

    Multi-output source nodes assign a list to their variable, so an
    expression like ``split_channels_1[1]`` selects the requested output port.
    """
    var = var_names[connection.source_id]
    source_node = pipeline.nodes.get(connection.source_id)
    if source_node is not None:
        source_spec = NODE_LIBRARY_BY_ID[source_node.operation_id]
        if source_spec.is_multi_output:
            return f"{var}[{int(connection.source_port)}]"
    return var


def _build_helpers() -> str:
    return (
        "def load_image(path):\n"
        f'{_INDENT}"""Load an array through the shared VIPP I/O registry."""\n'
        f"{_INDENT}return read_image(path).data\n\n\n"
        "def save_image(data, path):\n"
        f'{_INDENT}"""Write an image or table node output."""\n'
        f"{_INDENT}if is_table_data(data):\n"
        f"{_INDENT}{_INDENT}save_table_output(\n"
        f"{_INDENT}{_INDENT}{_INDENT}data,\n"
        f"{_INDENT}{_INDENT}{_INDENT}_table_output_path(path),\n"
        f"{_INDENT}{_INDENT}{_INDENT}overwrite=True,\n"
        f"{_INDENT}{_INDENT})\n"
        f"{_INDENT}{_INDENT}return\n"
        f"{_INDENT}write_image(data, path, overwrite=True)\n\n\n"
        "def _table_output_path(path):\n"
        f"{_INDENT}path = Path(path)\n"
        f"{_INDENT}if path.suffix.lower() in {{'.csv', '.tsv'}}:\n"
        f"{_INDENT}{_INDENT}return path\n"
        f"{_INDENT}return path.with_suffix('.csv')"
    )


def _build_main(source_ids: list[str], function_name: str) -> str:
    primary = source_ids[0] if source_ids else None
    feed = "load_image(in_path)" if primary else ""
    batch_feed = "load_image(source_path)" if primary else ""
    return (
        'def batch_process(input_dir, output_dir, pattern="*.tif"):\n'
        f'{_INDENT}"""Run the pipeline over every matching file in a folder."""\n'
        f"{_INDENT}input_dir = Path(input_dir)\n"
        f"{_INDENT}output_dir = Path(output_dir)\n"
        f"{_INDENT}output_dir.mkdir(parents=True, exist_ok=True)\n"
        f"{_INDENT}for source_path in sorted(input_dir.glob(pattern)):\n"
        f"{_INDENT}{_INDENT}results = {function_name}({batch_feed})\n"
        f"{_INDENT}{_INDENT}for name in OUTPUT_NODES:\n"
        f"{_INDENT}{_INDENT}{_INDENT}output = results.get(name)\n"
        f"{_INDENT}{_INDENT}{_INDENT}if output is None:\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}continue\n"
        f"{_INDENT}{_INDENT}{_INDENT}save_image(\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}output,\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}"
        f'output_dir / f"{{source_path.stem}}__{{name}}.ome.tif",\n'
        f"{_INDENT}{_INDENT}{_INDENT})\n\n\n"
        'if __name__ == "__main__":\n'
        f"{_INDENT}import argparse\n\n"
        f"{_INDENT}parser = argparse.ArgumentParser(\n"
        f'{_INDENT}{_INDENT}description="Run the exported napari-vipp pipeline."\n'
        f"{_INDENT})\n"
        f"{_INDENT}parser.add_argument(\n"
        f'{_INDENT}{_INDENT}"input", help="Image file or folder (batch mode)."\n'
        f"{_INDENT})\n"
        f'{_INDENT}parser.add_argument("output", help="Output file or folder.")\n'
        f"{_INDENT}parser.add_argument(\n"
        f'{_INDENT}{_INDENT}"--pattern", default="*.tif",'
        f' help="Glob used in folder mode."\n'
        f"{_INDENT})\n"
        f"{_INDENT}args = parser.parse_args()\n\n"
        f"{_INDENT}in_path = Path(args.input)\n"
        f"{_INDENT}if in_path.is_dir():\n"
        f"{_INDENT}{_INDENT}batch_process(in_path, args.output, pattern=args.pattern)\n"
        f"{_INDENT}else:\n"
        f"{_INDENT}{_INDENT}results = {function_name}({feed})\n"
        f"{_INDENT}{_INDENT}out_path = Path(args.output)\n"
        f"{_INDENT}{_INDENT}if len(OUTPUT_NODES) == 1:\n"
        f"{_INDENT}{_INDENT}{_INDENT}save_image(results[OUTPUT_NODES[0]], out_path)\n"
        f"{_INDENT}{_INDENT}else:\n"
        f"{_INDENT}{_INDENT}{_INDENT}out_path.mkdir(parents=True, exist_ok=True)\n"
        f"{_INDENT}{_INDENT}{_INDENT}for name in OUTPUT_NODES:\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}output = results.get(name)\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}if output is not None:\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}{_INDENT}save_image(\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}{_INDENT}{_INDENT}output,\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}{_INDENT}{_INDENT}"
        f'out_path / f"{{in_path.stem}}__{{name}}.ome.tif",\n'
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}{_INDENT})"
    )


def _terminal_nodes(pipeline: PrototypePipeline, order: list[str]) -> list[str]:
    explicit = [
        node_id
        for node_id in order
        if pipeline.nodes[node_id].operation_id == "batch_output"
    ]
    if explicit:
        return explicit
    consumed = {connection.source_id for connection in pipeline.connections}
    terminals = [node_id for node_id in order if node_id not in consumed]
    return terminals or list(order)


def _used_function_names(pipeline: PrototypePipeline, order: list[str]) -> list[str]:
    names = []
    for node_id in order:
        spec = NODE_LIBRARY_BY_ID[pipeline.nodes[node_id].operation_id]
        if spec.function is not None:
            names.append(spec.function.__name__)
    return names


def _unique_names(node_ids: list[str], *, prefix: str) -> dict[str, str]:
    names: dict[str, str] = {}
    used: set[str] = set()
    for node_id in node_ids:
        base = f"{prefix}_{_identifier(node_id)}"
        candidate = base
        suffix = 2
        while candidate in used:
            candidate = f"{base}_{suffix}"
            suffix += 1
        names[node_id] = candidate
        used.add(candidate)
    return names


def _identifier(node_id: str) -> str:
    cleaned = re.sub(r"\W", "_", node_id)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"n_{cleaned}"
    return cleaned


def _dedupe(items: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result
