"""Generate a runnable, headless Python script from a pipeline graph.

The exported script imports the pure functions from
:mod:`napari_vipp.core.operations` (which have no Qt/napari dependency) and
rebuilds the graph computation as a ``run_pipeline`` function plus a small batch
harness so a tuned workflow can be run over a folder of images without napari.
"""

from __future__ import annotations

import inspect
import re
from datetime import datetime, timezone

from napari_vipp.core.pipeline import NODE_LIBRARY_BY_ID, PrototypePipeline

_INDENT = " " * 4


def export_pipeline_to_python(
    pipeline: PrototypePipeline,
    *,
    function_name: str = "run_pipeline",
) -> str:
    """Return Python source code that reproduces the pipeline headlessly."""
    order = pipeline.topological_order()
    var_names = {node_id: _var_name(node_id) for node_id in order}

    source_ids = [
        node_id
        for node_id in order
        if not NODE_LIBRARY_BY_ID[pipeline.nodes[node_id].operation_id].has_input
    ]
    terminal_ids = _terminal_nodes(pipeline, order)
    used_functions = _used_function_names(pipeline, order)

    body_lines, missing = _build_function_body(
        pipeline, order, var_names, function_name
    )
    header = _build_header(pipeline)
    imports = _build_imports(used_functions)
    helpers = _build_helpers()
    constants = _build_constants(source_ids, terminal_ids)
    main = _build_main(source_ids)

    sections = [header, imports, constants, "\n".join(body_lines), helpers, main]
    document = "\n\n\n".join(section for section in sections if section)
    if missing:
        note = "\n".join(f"# NOTE: {line}" for line in missing)
        document = f"{document}\n\n\n{note}\n"
    return document.rstrip() + "\n"


def _build_header(pipeline: PrototypePipeline) -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    node_count = len(pipeline.nodes)
    connection_count = len(pipeline.connections)
    return (
        '"""Auto-generated by napari-vipp pipeline export.\n\n'
        f"Generated: {stamp}\n"
        f"Nodes: {node_count}  Connections: {connection_count}\n\n"
        "Run a single image:\n"
        "    python this_script.py input.tif output.tif\n\n"
        "Batch process a folder:\n"
        "    python this_script.py input_dir/ output_dir/ --pattern '*.tif'\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        "from pathlib import Path\n\n"
        "import numpy as np"
    )


def _build_imports(function_names: list[str]) -> str:
    names = sorted(set(function_names))
    inner = ",\n".join(f"{_INDENT}{name}" for name in names)
    operations = f"from napari_vipp.core.operations import (\n{inner},\n)"
    return (
        f"{operations}\n"
        "from napari_vipp.core.io import read_image, write_image\n"
        "from napari_vipp.core.tables import is_table_data, save_table_output"
    )


def _build_constants(source_ids: list[str], terminal_ids: list[str]) -> str:
    sources = ", ".join(repr(node_id) for node_id in source_ids)
    terminals = ", ".join(repr(node_id) for node_id in terminal_ids)
    return (
        f"SOURCE_NODES = ({sources}{',' if len(source_ids) == 1 else ''})\n"
        f"OUTPUT_NODES = ({terminals}{',' if len(terminal_ids) == 1 else ''})"
    )


def _build_function_body(
    pipeline: PrototypePipeline,
    order: list[str],
    var_names: dict[str, str],
    function_name: str,
) -> tuple[list[str], list[str]]:
    source_ids = [
        node_id
        for node_id in order
        if not NODE_LIBRARY_BY_ID[pipeline.nodes[node_id].operation_id].has_input
    ]
    params = []
    for index, node_id in enumerate(source_ids):
        param = _source_param_name(node_id)
        params.append(param if index == 0 else f"{param}=None")
    signature = ", ".join(params) if params else ""

    lines = [f"def {function_name}({signature}):"]
    docstring = '"""Execute the exported VIPP graph and return node outputs."""'
    lines.append(f"{_INDENT}{docstring}")

    missing: list[str] = []
    for node_id in order:
        node = pipeline.nodes[node_id]
        spec = NODE_LIBRARY_BY_ID[node.operation_id]
        var = var_names[node_id]
        if not spec.has_input:
            lines.append(f"{_INDENT}{var} = {_source_param_name(node_id)}")
            continue

        connections = pipeline._input_connections(node_id)
        if spec.function is None or not connections:
            lines.append(f"{_INDENT}{var} = None  # {node.title}: no connected input")
            continue

        call = _build_call(pipeline, node, spec, connections, var_names)
        lines.append(f"{_INDENT}{var} = {call}")
        if node.operation_id == "combine_channels":
            if "channel_axis" not in node.params:
                missing.append(
                    "combine_channels was exported without a stored channel_axis; "
                    "run the pipeline once in napari to store the metadata-derived "
                    "axis before export."
                )
        if spec.is_multi_output and node_id in _terminal_nodes(pipeline, order):
            missing.append(
                f"{node.title} ({node_id}) produces multiple outputs but nothing "
                "consumes them; connect its output ports so the script can route "
                "each channel."
            )

    returns = ", ".join(
        f"{node_id!r}: {var_names[node_id]}" for node_id in order
    )
    lines.append(f"{_INDENT}return {{{returns}}}")
    return lines, _dedupe(missing)


def _build_call(pipeline, node, spec, connections, var_names) -> str:
    fn_name = spec.function.__name__
    accepted = list(inspect.signature(spec.function).parameters)
    data_param = accepted[0] if accepted else ""
    kwargs = {
        key: value
        for key, value in node.params.items()
        if key in accepted and key != data_param
    }
    kwargs_text = ", ".join(f"{key}={value!r}" for key, value in kwargs.items())

    multi_input = node.max_inputs is None or node.max_inputs != 1
    if multi_input:
        inputs = ", ".join(
            _source_ref(pipeline, conn, var_names) for conn in connections
        )
        first_arg = f"[{inputs}]"
    else:
        first_arg = _source_ref(pipeline, connections[0], var_names)

    if kwargs_text:
        return f"{fn_name}({first_arg}, {kwargs_text})"
    return f"{fn_name}({first_arg})"


def _source_ref(pipeline, connection, var_names) -> str:
    """Return the variable expression for one input connection.

    Multi-output source nodes assign a list to their variable, so an
    expression like ``split_channels_1[1]`` selects the requested output port.
    """
    var = var_names[connection.source_id]
    source_node = pipeline.nodes.get(connection.source_id)
    if source_node is not None:
        source_spec = NODE_LIBRARY_BY_ID[source_node.operation_id]
        if source_spec.is_multi_output:
            return f"{var}[{int(connection.source_port)}]"
    return var


def _build_helpers() -> str:
    return (
        "def load_image(path):\n"
        f'{_INDENT}"""Load an array through the shared VIPP I/O registry."""\n'
        f"{_INDENT}return read_image(path).data\n\n\n"
        "def save_image(data, path):\n"
        f'{_INDENT}"""Write an image or table node output."""\n'
        f"{_INDENT}if is_table_data(data):\n"
        f"{_INDENT}{_INDENT}save_table_output(\n"
        f"{_INDENT}{_INDENT}{_INDENT}data,\n"
        f"{_INDENT}{_INDENT}{_INDENT}_table_output_path(path),\n"
        f"{_INDENT}{_INDENT}{_INDENT}overwrite=True,\n"
        f"{_INDENT}{_INDENT})\n"
        f"{_INDENT}{_INDENT}return\n"
        f"{_INDENT}write_image(data, path, overwrite=True)\n\n\n"
        "def _table_output_path(path):\n"
        f"{_INDENT}path = Path(path)\n"
        f"{_INDENT}if path.suffix.lower() in {{'.csv', '.tsv'}}:\n"
        f"{_INDENT}{_INDENT}return path\n"
        f"{_INDENT}return path.with_suffix('.csv')"
    )


def _build_main(source_ids: list[str]) -> str:
    primary = source_ids[0] if source_ids else None
    feed = "load_image(in_path)" if primary else ""
    return (
        "def batch_process(input_dir, output_dir, pattern=\"*.tif\"):\n"
        f'{_INDENT}"""Run the pipeline over every matching file in a folder."""\n'
        f"{_INDENT}input_dir = Path(input_dir)\n"
        f"{_INDENT}output_dir = Path(output_dir)\n"
        f"{_INDENT}output_dir.mkdir(parents=True, exist_ok=True)\n"
        f"{_INDENT}for source_path in sorted(input_dir.glob(pattern)):\n"
        f"{_INDENT}{_INDENT}results = run_pipeline(load_image(source_path))\n"
        f"{_INDENT}{_INDENT}for name in OUTPUT_NODES:\n"
        f"{_INDENT}{_INDENT}{_INDENT}output = results.get(name)\n"
        f"{_INDENT}{_INDENT}{_INDENT}if output is None:\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}continue\n"
        f"{_INDENT}{_INDENT}{_INDENT}save_image(\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}output,\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}"
        f'output_dir / f"{{source_path.stem}}__{{name}}.ome.tif",\n'
        f"{_INDENT}{_INDENT}{_INDENT})\n\n\n"
        'if __name__ == "__main__":\n'
        f"{_INDENT}import argparse\n\n"
        f"{_INDENT}parser = argparse.ArgumentParser(\n"
        f'{_INDENT}{_INDENT}description="Run the exported napari-vipp pipeline."\n'
        f"{_INDENT})\n"
        f"{_INDENT}parser.add_argument(\n"
        f'{_INDENT}{_INDENT}"input", help="Image file or folder (batch mode)."\n'
        f"{_INDENT})\n"
        f'{_INDENT}parser.add_argument("output", help="Output file or folder.")\n'
        f"{_INDENT}parser.add_argument(\n"
        f'{_INDENT}{_INDENT}"--pattern", default="*.tif",'
        f' help="Glob used in folder mode."\n'
        f"{_INDENT})\n"
        f"{_INDENT}args = parser.parse_args()\n\n"
        f"{_INDENT}in_path = Path(args.input)\n"
        f"{_INDENT}if in_path.is_dir():\n"
        f"{_INDENT}{_INDENT}batch_process(in_path, args.output, pattern=args.pattern)\n"
        f"{_INDENT}else:\n"
        f"{_INDENT}{_INDENT}results = run_pipeline({feed})\n"
        f"{_INDENT}{_INDENT}out_path = Path(args.output)\n"
        f"{_INDENT}{_INDENT}if len(OUTPUT_NODES) == 1:\n"
        f"{_INDENT}{_INDENT}{_INDENT}save_image(results[OUTPUT_NODES[0]], out_path)\n"
        f"{_INDENT}{_INDENT}else:\n"
        f"{_INDENT}{_INDENT}{_INDENT}out_path.mkdir(parents=True, exist_ok=True)\n"
        f"{_INDENT}{_INDENT}{_INDENT}for name in OUTPUT_NODES:\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}output = results.get(name)\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}if output is not None:\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}{_INDENT}save_image(\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}{_INDENT}{_INDENT}output,\n"
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}{_INDENT}{_INDENT}"
        f'out_path / f"{{in_path.stem}}__{{name}}.ome.tif",\n'
        f"{_INDENT}{_INDENT}{_INDENT}{_INDENT}{_INDENT})"
    )


def _terminal_nodes(pipeline: PrototypePipeline, order: list[str]) -> list[str]:
    consumed = {connection.source_id for connection in pipeline.connections}
    terminals = [node_id for node_id in order if node_id not in consumed]
    return terminals or list(order)


def _used_function_names(pipeline: PrototypePipeline, order: list[str]) -> list[str]:
    names = []
    for node_id in order:
        spec = NODE_LIBRARY_BY_ID[pipeline.nodes[node_id].operation_id]
        if spec.function is not None:
            names.append(spec.function.__name__)
    return names


def _var_name(node_id: str) -> str:
    return f"v_{_identifier(node_id)}"


def _source_param_name(node_id: str) -> str:
    return f"src_{_identifier(node_id)}"


def _identifier(node_id: str) -> str:
    cleaned = re.sub(r"\W", "_", node_id)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"n_{cleaned}"
    return cleaned


def _dedupe(items: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result
