"""Headless installation discovery, review, and managed execution for VIPP."""

from napari_vipp.installer.discovery import (
    DiscoveryError,
    DiscoveryServices,
    discover_installation,
)
from napari_vipp.installer.engine import (
    AuthorizationError,
    CancellationToken,
    ExecutionAuthorization,
    InstallProgress,
    InstallResult,
    InstallStatus,
    ManagedInstallerEngine,
    ManagedTargetInspection,
    ManagedTargetKind,
    PreparationError,
    PreparedShortcut,
    PreparedTransaction,
    ProgressStage,
    ResolutionError,
    RollbackReport,
    inspect_managed_target,
)
from napari_vipp.installer.models import (
    ComputeTrack,
    DiscoverySnapshot,
    InstallMode,
    InstallPlan,
    InstallRequest,
    PlanStatus,
    ReleaseSpec,
    ShortcutScope,
)
from napari_vipp.installer.planner import (
    PlannerError,
    create_install_plan,
    current_release_spec,
)
from napari_vipp.installer.uninstall import (
    ManagedUninstaller,
    PreparedUninstall,
    RegistryRegistrationPlan,
    UninstallAuthorization,
    UninstallResult,
    UninstallStatus,
    WindowsRegistryBackend,
    registry_key_for_track,
)

__all__ = [
    "ComputeTrack",
    "AuthorizationError",
    "CancellationToken",
    "DiscoveryError",
    "DiscoveryServices",
    "DiscoverySnapshot",
    "InstallMode",
    "InstallPlan",
    "InstallProgress",
    "InstallRequest",
    "InstallResult",
    "InstallStatus",
    "ExecutionAuthorization",
    "ManagedInstallerEngine",
    "ManagedUninstaller",
    "ManagedTargetInspection",
    "ManagedTargetKind",
    "PlanStatus",
    "PlannerError",
    "PreparationError",
    "PreparedShortcut",
    "PreparedTransaction",
    "PreparedUninstall",
    "ProgressStage",
    "ReleaseSpec",
    "ShortcutScope",
    "ResolutionError",
    "RegistryRegistrationPlan",
    "RollbackReport",
    "UninstallAuthorization",
    "UninstallResult",
    "UninstallStatus",
    "WindowsRegistryBackend",
    "create_install_plan",
    "current_release_spec",
    "discover_installation",
    "inspect_managed_target",
    "registry_key_for_track",
]
